#!/usr/bin/env bash
# Pre-build setup for the Flatpak target (local developer workflow).
#
# Run from the repo root:
#   guix shell -m manifest.scm -- bash flatpak/setup.sh
#
# Or outside a Guix shell (needs Python + pip on PATH):
#   bash flatpak/setup.sh
#
# Re-run whenever package-lock.json changes.
# generated-sources.json is .gitignore'd — it is regenerated by CI on every run.
#
# Flatpak runtimes (one-time):
#   flatpak remote-add --if-not-exists flathub \
#     https://dl.flathub.org/repo/flathub.flatpakrepo
#   flatpak install flathub \
#     org.freedesktop.Platform//24.08 \
#     org.freedesktop.Sdk//24.08 \
#     org.freedesktop.Sdk.Extension.node20//24.08 \
#     org.electronjs.Electron2.BaseApp//24.08
#
# flatpak-builder (one-time):
#   flatpak install flathub org.flatpak.Builder

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if ! command -v flatpak-node-generator &>/dev/null; then
  if ! command -v pip &>/dev/null; then
    echo "Error: pip not found. Run inside: guix shell -m manifest.scm" >&2
    exit 1
  fi
  echo "Installing flatpak-node-generator from git..."
  pip install --user --quiet \
    "git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node"
fi

echo "Generating npm offline sources from package-lock.json..."
flatpak-node-generator \
  --no-requests-cache \
  npm \
  "${REPO_ROOT}/package-lock.json" \
  -o "${SCRIPT_DIR}/generated-sources.json"

echo "Done. flatpak/generated-sources.json is ready (not committed — regenerated by CI)."
echo ""
echo "To build the Flatpak locally:"
echo "  SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \\"
echo "  flatpak run org.flatpak.Builder --user --install --force-clean \\"
echo "    build-flatpak flatpak/com.blackthorn.daoc.Launcher.yml"
